# Generated by Django 5.0 on 2023-12-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_alter_women_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='women/'),
        ),
    ]
