# Generated by Django 5.0 on 2024-01-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_category_alter_women_image_women_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['nationality'], 'verbose_name': 'Women', 'verbose_name_plural': 'Women'},
        ),
    ]
